### ISSUE TITLE
HOW DO I CREATE BOTTOM COPYRIGHT TEXT HELP

### ISSUE THREAD

**Issue by Program27** [ArViNBots/unknownhome-game#2]
pls how do i do that

**Comment by ArViNBots** [comment]
Typically, a copyright notice contains four different elements, each of which are brief but important.

The Copyright Symbol
The Year of the Creation
The Name of the Author
A Rights Statement


https://markdowntohtml.com/

![image](https://user-images.githubusercontent.com/72962960/104729313-3c6b0900-5706-11eb-9dfe-6a69d5b2be62.png)

**Comment by ArViNBots** [comment]
maybe like this:

![image](https://user-images.githubusercontent.com/72962960/104729655-bdc29b80-5706-11eb-9cdc-e4469210fbff.png)
